# docker-compose.yml
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENWEATHER_API_KEY=3981d24f49b14ae702f3fd85fad6f46e